// SAdK shim: a proxy wsock32.dll. tincat3.dll imports all of its sockets from WSOCK32.dll by ordinal; every export is
// forwarded by ordinal to the system wsock32.dll (thunks.S, generated by gen.py). On the DRM-free SADK.exe it is the
// mod host: it loads <game>\mods\* through sadkmod (sadkmod/README.md, mods/README.md) before the game's own code
// runs. Everything else is a mod: the host bridge is mods/gamehostbridge, map sharing mods/assetshare.
//
//   main.cpp        DllMain, the forwarding table, start-up (before SADK.exe's entry point) and mod loading
#pragma once
#include <winsock2.h>
#include <windows.h>

#include <sadkmod/sadkmod.hpp>

#include "ordinals.h"

extern "C" void *real_ptrs[N_EXPORTS];   // the system wsock32.dll's exports, by index (gen.py)
